### ISSUE TITLE
Figure out how cargo-cache in GitHub workflow works

### ISSUE THREAD

**Issue by tisonkun** [engula/engula#188]
@huachaohuang @Xuanwo it seems we just cannot skip the install step even if cargo cache hit.

Cargo cache can already speed up the installation by `cargo-install` cache hit logic, we should always run `cargo install` to avoid false positive.

Remove `if: steps.cache.outputs.cache-hit != 'true'` lines should work. @Xuanwo we may later figure why current settings create false positive.

_Originally posted by @tisonkun in https://github.com/engula/engula/pull/185#issuecomment-992226207_

**Comment by tisonkun** [comment]
@mati865 @est31 it seems caching `cargo-udeps` binary and skip the installation step could generate false postive.

The workflow report is [here](https://github.com/engula/engula/runs/4503586427?check_suite_focus=true) and you can find the workflow file [here](https://github.com/engula/engula/actions/runs/1571996808/workflow). Do you have ideas about what the problem is?

**Comment by mati865** [comment]
@tisonkun this action doesn't cache binaries: https://github.com/marketplace/actions/rust-cache#cache-details
Also you shouldn't avoid installing when cache was hit, you need to see if there is an update. I think Cargo will handle it by default when you always do cargo install.

**Comment by tisonkun** [comment]
> Also you shouldn't avoid installing when cache was hit, you need to see if there is an update. I think Cargo will handle it by default when you always do cargo install.

Thanks! I also saw this point when proving locally.

**Comment by tisonkun** [comment]
@mati865 we don't just use the rust-cache action but write a composition for it. I think it cache the binaries by

```yml
    - name: Cache cargo registry
      id: cache
      uses: actions/cache@v2
      with:
        path: |
*         ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
```

And it's strange that skipping installation does no hard for `cargo-audit` ([ref](https://github.com/engula/engula/runs/4530073346?check_suite_focus=true)) but throws an error on `cargo-udeps`.

**Comment by DCjanus** [comment]
Looks like this workflow not work as we expected/

Loading cache to speed up `cargo install`, cache key should be `date` rather than `Cargo.lock`

```yaml
name: 'Cargo Cache'
description: 'Cache cargo installation'
outputs:
  cache-hit:
    description: "Whether this cache hit or not"
    value: ${{ steps.cache.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      shell: bash

    - name: Cache cargo registry
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ steps.get-date.outputs.date }}
```
